type: hallway

initial_state: {x: 0.0, y: 0.0, vx: 0.0, vy: 0.0}
goal: {x: 10.0, y: 10.0}
guidance: {waypoint_threshold: 0.2}

planner:
  allow_diagonal: true
  fuel_rate: 1.0
  max_waypoint_distance: 1.0
  waypoint_cost: 0.02
  turn_cost_weight: 0.5
  nominal_speed: 2.0
  proximity_sigma: 0.06
  allow_disallowed: false
  max_cost: .inf
